import { customEmojis } from "./utils.js";

export const achievementsByUpdate = {
  night_owl_messages:   ["night_owl", "insone"],
  messages_sent:        ["chatterbox", "first_message", "chat_legend"],
  caps_lock_messages:   ["caps_addict"],
  question_marks:       ["question_everything"],
  morning_messages:     ["good_morning"],
  laught_messages:      ["funny_today"],
  swears_count:         ["dirty_mouth", "vocabulario_rico"],
  long_questions:       ["philosopher"],
  caps_streak:          ["urgency"],
  specific_time_messages: ["devil_message"],
  suspense_messages:    ["misterioso"],
  textao_messages:      ["textao_enem"],
  monologo_streak:      ["monologo"],
  bot_commands_used:    ["bot_addicted"],
  mentions_sent:        ["stalker"],
  mentions_received:    ["popular"],
  bounties_placed:      ["patrocinador_do_caos", "agiota_profissional", "el_capo"],
  bounties_claimed:     ["cacador_de_recompensas", "cacador_de_cabecas", "xerife_do_oeste"],
  times_bountied:       ["alvo_facil", "alvo_procurado", "inimigo_publico_numero_um"],
  total_robberies:      ["primeiro_roubo", "dependente"],
  lifetime_tiger_spins: ["tigre_centuria"],
  tiger_jackpots:       ["tigrinho_lenda"],
  tiger_losses:         ["apostador", "masoquista"],
  tiger_wins:           ["sortudo_no_tigre", "tigreiro_nato"],
  consecutive_robbery_losses: ["ladrao_pessimo"],
  total_chars_donated:  ["generoso"],
};

export const achievements = [
  {
    key: "ghost",
    title: "Fantasma",
    icon: customEmojis.skullGlowing,
    description: "30 dias sem mensagens e voltou",
    charPoints: 5000,
    category: "special",
    secret: false,
    hiddenDescription: null,
    check: () => false,
    progress: null,
  },
  {
    key: "archaeologist",
    title: "O Arqueólogo",
    icon: customEmojis.writingGOOD,
    description: "Desenterre o passado...",
    hiddenDescription: "Respondeu a uma mensagem de mais de 1 ano atrás",
    charPoints: 3000,
    category: "special",
    secret: true,
    check: () => false,
    progress: null,
  },
  {
    key: "the_chosen_one",
    title: "O Escolhido",
    icon: customEmojis.mineLegendHero,
    description: "Você tem 0.01% de sorte",
    hiddenDescription: "chance aleatoria de ao usar um comando ganhar essa conquista",
    charPoints: 10000,
    category: "special",
    secret: true,
    check: () => false,
    progress: null,
  },
  {
    key: "caps_addict",
    title: "VICIADO EM CAPS LOCK",
    icon: "📢",
    description: "50 mensagens gritando",
    charPoints: 800,
    category: "activity",
    secret: false,
    hiddenDescription: null,
    check: (stats) => stats.caps_lock_messages >= 50,
    progress: (stats) => ({ current: Math.min(stats.caps_lock_messages ?? 0, 50), total: 50 }),
  },
  {
    key: "night_owl",
    title: "Coruja Noturna",
    icon: "🦉",
    description: "Mandou 100 mensagens na madrugada (2h-6h)",
    charPoints: 1000,
    category: "activity",
    secret: false,
    hiddenDescription: null,
    check: (stats) => stats.night_owl_messages >= 100,
    progress: (stats) => ({ current: Math.min(stats.night_owl_messages ?? 0, 100), total: 100 }),
  },
  {
    key: "popular",
    title: "Popularzinho",
    icon: "⭐",
    description: "200 menções recebidas",
    charPoints: 2000,
    category: "social",
    secret: false,
    hiddenDescription: null,
    check: (stats) => stats.mentions_received >= 200,
    progress: (stats) => ({ current: Math.min(stats.mentions_received ?? 0, 200), total: 200 }),
  },
  {
    key: "stalker",
    title: "Stalker",
    icon: "👀",
    description: "Mencionou os outros 300 vezes",
    charPoints: 1500,
    category: "social",
    secret: false,
    hiddenDescription: null,
    check: (stats) => stats.mentions_sent >= 300,
    progress: (stats) => ({ current: Math.min(stats.mentions_sent ?? 0, 300), total: 300 }),
  },
  {
    key: "question_everything",
    title: "Curioso",
    icon: "❓",
    description: "Fez 150 perguntas no chat",
    charPoints: 2000,
    category: "activity",
    secret: false,
    hiddenDescription: null,
    check: (stats) => stats.question_marks >= 150,
    progress: (stats) => ({ current: Math.min(stats.question_marks ?? 0, 150), total: 150 }),
  },
  {
    key: "chatterbox",
    title: "Tagarela",
    icon: "💬",
    description: "1.000 mensagens enviadas",
    charPoints: 1850,
    category: "activity",
    secret: false,
    hiddenDescription: null,
    check: (stats) => stats.messages_sent >= 1000,
    progress: (stats) => ({ current: Math.min(stats.messages_sent ?? 0, 1000), total: 1000 }),
  },
  {
    key: "first_message",
    title: "Primeiro Passo",
    icon: customEmojis.hearts,
    description: "Enviou sua primeira mensagem",
    charPoints: 100,
    category: "activity",
    secret: false,
    hiddenDescription: null,
    check: (stats) => stats.messages_sent >= 1,
    progress: (stats) => ({ current: Math.min(stats.messages_sent ?? 0, 1), total: 1 }),
  },
  {
    key: "good_morning",
    title: "Acorda!!!",
    icon: customEmojis.hello,
    description: "Mandou 'bom dia' no chat",
    charPoints: 400,
    category: "activity",
    secret: false,
    hiddenDescription: null,
    check: (stats) => stats.morning_messages >= 1,
    progress: (stats) => ({ current: Math.min(stats.morning_messages ?? 0, 1), total: 1 }),
  },
  {
    key: "monologo",
    title: "Esquizofrenico",
    icon: "🗣️",
    description: "10 mensagens seguidas falando sozinho",
    charPoints: 400,
    category: "activity",
    secret: false,
    hiddenDescription: null,
    check: (stats) => stats.monologo_streak >= 10,
    progress: (stats) => ({ current: Math.min(stats.monologo_streak ?? 0, 10), total: 10 }),
  },
  {
    key: "devil_message",
    title: "DIABOLICO",
    icon: customEmojis.pepeCruz,
    description: "Mandou mensagem exatamente às 03:33",
    charPoints: 1500,
    category: "activity",
    secret: true,
    hiddenDescription: null,
    check: (stats) => stats.specific_time_messages >= 1,
    progress: null,
  },
  {
    key: "reincarnation",
    title: "Reencarnou",
    icon: customEmojis.skullGlowing,
    description: "Voltou depois de 1 ano sem mandar mensagem",
    charPoints: 50000,
    category: "special",
    secret: false,
    hiddenDescription: null,
    check: () => false,
    progress: null,
  },
  {
    key: "chat_legend",
    title: "Inimigo da Vida Social",
    icon: "🌱",
    description: "Enviou 10.000 mensagens",
    charPoints: 10000,
    category: "activity",
    secret: false,
    hiddenDescription: null,
    check: (stats) => stats.messages_sent >= 10000,
    progress: (stats) => ({ current: Math.min(stats.messages_sent ?? 0, 10000), total: 10000 }),
  },
  {
    key: "urgency",
    title: "Calma Calabreso",
    icon: "🚨",
    description: "5 mensagens seguidas em CAPS",
    charPoints: 100,
    category: "activity",
    secret: false,
    hiddenDescription: null,
    check: (stats) => stats.caps_streak >= 5,
    progress: (stats) => ({ current: Math.min(stats.caps_streak ?? 0, 5), total: 5 }),
  },
  {
    key: "philosopher",
    title: "Filósofo",
    icon: customEmojis.pepeThinking,
    description: "Pergunta com mais de 100 caracteres",
    charPoints: 150,
    category: "activity",
    secret: false,
    hiddenDescription: null,
    check: (stats) => stats.long_questions >= 1,
    progress: (stats) => ({ current: Math.min(stats.long_questions ?? 0, 1), total: 1 }),
  },
  {
    key: "funny_today",
    title: "paliasso",
    icon: customEmojis.pepeClown,
    description: "Deu uma risada muito longa (kkkkkk)",
    charPoints: 200,
    category: "activity",
    secret: false,
    hiddenDescription: null,
    check: (stats) => stats.laught_messages >= 1,
    progress: (stats) => ({ current: Math.min(stats.laught_messages ?? 0, 1), total: 1 }),
  },
  {
    key: "dirty_mouth",
    title: "Boca Suja",
    icon: "🧼",
    description: "Falou palavrao 50 vezes",
    charPoints: 300,
    category: "verbal",
    secret: false,
    hiddenDescription: null,
    check: (stats) => stats.swears_count >= 50,
    progress: (stats) => ({ current: Math.min(stats.swears_count ?? 0, 50), total: 50 }),
  },
  {
    key: "bot_addicted",
    title: "Entusiasta do Bot",
    icon: "🤖",
    description: "50 comandos usados",
    charPoints: 400,
    category: "activity",
    secret: false,
    hiddenDescription: null,
    check: (stats) => stats.bot_commands_used >= 50,
    progress: (stats) => ({ current: Math.min(stats.bot_commands_used ?? 0, 50), total: 50 }),
  },
  {
    key: "misterioso",
    title: "Misterioso",
    icon: customEmojis.pepeMysticCape,
    description: "15 Mensagens com reticências...",
    charPoints: 150,
    category: "activity",
    secret: false,
    hiddenDescription: null,
    check: (stats) => stats.suspense_messages >= 15,
    progress: (stats) => ({ current: Math.min(stats.suspense_messages ?? 0, 15), total: 15 }),
  },
  {
    key: "textao_enem",
    title: "Escritor maldito",
    icon: customEmojis.writingGOOD,
    description: "Mandou um textão com mais de 600 caracteres",
    charPoints: 800,
    category: "activity",
    secret: false,
    hiddenDescription: null,
    check: (stats) => stats.textao_messages >= 1,
    progress: (stats) => ({ current: Math.min(stats.textao_messages ?? 0, 1), total: 1 }),
  },
  {
    key: "insone",
    title: "Insonia PLUS",
    icon: customEmojis.mineNightVision,
    description: "500 mensagens de madrugada (2h-6h).",
    charPoints: 1500,
    category: "activity",
    secret: false,
    hiddenDescription: null,
    check: (stats) => stats.night_owl_messages >= 500,
    progress: (stats) => ({ current: Math.min(stats.night_owl_messages ?? 0, 500), total: 500 }),
  },
  {
    key: "vocabulario_rico",
    title: "Vocabulário Rico",
    icon: customEmojis.infested,
    description: "200 palavrões ditos",
    charPoints: 1000,
    category: "verbal",
    secret: false,
    hiddenDescription: null,
    check: (stats) => stats.swears_count >= 200,
    progress: (stats) => ({ current: Math.min(stats.swears_count ?? 0, 200), total: 200 }),
  },
  {
    key: "dependente",
    title: "Ladrão profissional",
    icon: customEmojis.pepeJail,
    description: "Roubou 30 vezes no total.",
    charPoints: 700,
    category: "robbery",
    secret: false,
    hiddenDescription: null,
    check: (stats) => (stats.total_robberies || 0) >= 30,
    progress: (stats) => ({ current: Math.min(stats.total_robberies ?? 0, 30), total: 30 }),
  },
  {
    key: "apostador",
    title: "Apostador Ruim",
    icon: customEmojis.pepeSus,
    description: "Perdeu 20 vezes no tigre. Talento natural.",
    charPoints: 500,
    category: "tiger",
    secret: false,
    hiddenDescription: null,
    check: (stats) => (stats.tiger_losses || 0) >= 20,
    progress: (stats) => ({ current: Math.min(stats.tiger_losses ?? 0, 20), total: 20 }),
  },
  {
    key: "generoso",
    title: "Filantropo",
    icon: "🤲",
    description: "Doou 10.000 caracteres no total",
    charPoints: 2500,
    category: "special",
    secret: false,
    hiddenDescription: null,
    check: (stats) => (stats.total_chars_donated || 0) >= 10000,
    progress: (stats) => ({ current: Math.min(stats.total_chars_donated ?? 0, 10000), total: 10000 }),
  },
  {
    key: "tigrinho_lenda",
    title: "CEO do tigrinho",
    icon: "🎰",
    description: "Ganhou 2 jackpots no tigre",
    charPoints: 100,
    category: "tiger",
    secret: false,
    hiddenDescription: null,
    check: (stats) => (stats.tiger_jackpots || 0) >= 2,
    progress: (stats) => ({ current: Math.min(stats.tiger_jackpots ?? 0, 2), total: 2 }),
  },
  {
    key: "tigre_centuria",
    title: "Viciado no Tigrinho",
    icon: "🐯",
    description: "Jogou o tigre 100 vezes no total",
    charPoints: 1500,
    category: "tiger",
    secret: false,
    hiddenDescription: null,
    check: (stats) => (stats.lifetime_tiger_spins || 0) >= 100,
    progress: (stats) => ({ current: Math.min(stats.lifetime_tiger_spins ?? 0, 100), total: 100 }),
  },
  {
    key: "cacador_de_recompensas",
    title: "CAÇADOR DE RECOMPENSAS",
    icon: "🏹",
    description: "Pegou 10 recompensas na cabeça de alguém",
    charPoints: 1200,
    category: "bounty",
    secret: false,
    hiddenDescription: null,
    check: (stats) => (stats.bounties_claimed || 0) >= 10,
    progress: (stats) => ({ current: Math.min(stats.bounties_claimed ?? 0, 10), total: 10 }),
  },
  {
    key: "cacador_de_cabecas",
    title: "CAÇADOR DE CABEÇAS",
    icon: customEmojis.skullAndRoses,
    description: "Pegou 20 recompensas como um verdadeiro carniceiro",
    charPoints: 2800,
    category: "bounty",
    secret: false,
    hiddenDescription: null,
    check: (stats) => (stats.bounties_claimed || 0) >= 20,
    progress: (stats) => ({ current: Math.min(stats.bounties_claimed ?? 0, 20), total: 20 }),
  },
  {
    key: "xerife_do_oeste",
    title: "XERIFE DO OESTE",
    icon: customEmojis.pepePolice,
    description: "Pegou 50 recompensas. A lei é você agora, porra",
    charPoints: 6000,
    category: "bounty",
    secret: false,
    hiddenDescription: null,
    check: (stats) => (stats.bounties_claimed || 0) >= 50,
    progress: (stats) => ({ current: Math.min(stats.bounties_claimed ?? 0, 50), total: 50 }),
  },
  {
    key: "patrocinador_do_caos",
    title: "PATROCINADOR DO CAOS",
    icon: customEmojis.pepeSeenExplosion,
    description: "Pagou 10 recompensas na cabeça dos outros",
    charPoints: 1000,
    category: "bounty",
    secret: false,
    hiddenDescription: null,
    check: (stats) => (stats.bounties_placed || 0) >= 10,
    progress: (stats) => ({ current: Math.min(stats.bounties_placed ?? 0, 10), total: 10 }),
  },
  {
    key: "agiota_profissional",
    title: "AGIOTA PROFISSIONAL",
    icon: customEmojis.agiotaFedora,
    description: "Pagou 20 recompensas.",
    charPoints: 2500,
    category: "bounty",
    secret: false,
    hiddenDescription: null,
    check: (stats) => (stats.bounties_placed || 0) >= 20,
    progress: (stats) => ({ current: Math.min(stats.bounties_placed ?? 0, 20), total: 20 }),
  },
  {
    key: "el_capo",
    title: "EL CAPO",
    icon: customEmojis.verifiedGolden,
    description: "Pagou 50 recompensas. O chefão do submundo",
    charPoints: 6500,
    category: "bounty",
    secret: false,
    hiddenDescription: null,
    check: (stats) => (stats.bounties_placed || 0) >= 50,
    progress: (stats) => ({ current: Math.min(stats.bounties_placed ?? 0, 50), total: 50 }),
  },
  {
    key: "alvo_facil",
    title: "ALVO FÁCIL",
    icon: customEmojis.rainbowSheep,
    description: "Recebeu 10 recompensas em sua cabeça.",
    charPoints: 800,
    category: "bounty",
    secret: false,
    hiddenDescription: null,
    check: (stats) => (stats.times_bountied || 0) >= 10,
    progress: (stats) => ({ current: Math.min(stats.times_bountied ?? 0, 10), total: 10 }),
  },
  {
    key: "alvo_procurado",
    title: "ALVO PROCURADO",
    icon: "💸",
    description: "Recebeu 25 recompensas em sua cabeça.",
    charPoints: 2200,
    category: "bounty",
    secret: false,
    hiddenDescription: null,
    check: (stats) => (stats.times_bountied || 0) >= 25,
    progress: (stats) => ({ current: Math.min(stats.times_bountied ?? 0, 25), total: 25 }),
  },
  {
    key: "inimigo_publico_numero_um",
    title: "INIMIGO PÚBLICO Nº 1",
    icon: customEmojis.pointingGun,
    description: "Recebeu 50 recompensas em sua cabeça.",
    charPoints: 5500,
    category: "bounty",
    secret: false,
    hiddenDescription: null,
    check: (stats) => (stats.times_bountied || 0) >= 50,
    progress: (stats) => ({ current: Math.min(stats.times_bountied ?? 0, 50), total: 50 }),
  },
  {
    key: "primeiro_roubo",
    title: "Iniciante do Crime",
    icon: "🦹",
    description: "Cometeu seu primeiro roubo.",
    charPoints: 100,
    category: "robbery",
    secret: false,
    hiddenDescription: null,
    check: (stats) => (stats.total_robberies || 0) >= 1,
    progress: (stats) => ({ current: Math.min(stats.total_robberies ?? 0, 1), total: 1 }),
  },
  {
    key: "sortudo_no_tigre",
    title: "Sortudo no Tigre",
    icon: "🍀",
    description: "Ganhou no tigre 10 vezes.",
    charPoints: 600,
    category: "tiger",
    secret: false,
    hiddenDescription: null,
    check: (stats) => (stats.tiger_wins || 0) >= 10,
    progress: (stats) => ({ current: Math.min(stats.tiger_wins ?? 0, 10), total: 10 }),
  },
  {
    key: "tigreiro_nato",
    title: "Tigreiro NATO",
    icon: "🐯",
    description: "Ganhou no tigre 50 vezes.",
    charPoints: 2000,
    category: "tiger",
    secret: false,
    hiddenDescription: null,
    check: (stats) => (stats.tiger_wins || 0) >= 50,
    progress: (stats) => ({ current: Math.min(stats.tiger_wins ?? 0, 50), total: 50 }),
  },
  {
    key: "masoquista",
    title: "Masoquista",
    icon: customEmojis.pepeCry,
    description: "Perdeu no tigre 100 vezes e continua jogando.",
    charPoints: 1200,
    category: "tiger",
    secret: false,
    hiddenDescription: null,
    check: (stats) => (stats.tiger_losses || 0) >= 100,
    progress: (stats) => ({ current: Math.min(stats.tiger_losses ?? 0, 100), total: 100 }),
  },
  {
    key: "ladrao_pessimo",
    title: "PIOR LADRÃO",
    icon: customEmojis.sadge,
    description: "Falhou 10 roubos consecutivos",
    charPoints: 600,
    category: "robbery",
    secret: false,
    hiddenDescription: null,
    check: (stats) => (stats.consecutive_robbery_losses || 0) >= 10,
    progress: (stats) => ({ current: Math.min(stats.consecutive_robbery_losses ?? 0, 10), total: 10 }),
  },
];

export const getAchievementByKey = (key) =>
  achievements.find((ach) => ach.key === key);

export const getUnlockedAchievements = (stats) =>
  achievements.filter((ach) => ach.check(stats));

export const getAchievementsByCategory = (category) =>
  achievements.filter((ach) => ach.category === category);

export const checkAllAchievements = (stats) => {
  const unlocked = [];
  for (const ach of achievements) {
    if (ach.check(stats)) unlocked.push(ach);
  }
  return unlocked;
};